FROM nginx:1.27-alpine

# For CN users, consider using: FROM registry.cn-hangzhou.aliyuncs.com/library/nginx:1.27-alpine

COPY deploy/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
